[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simplemath-new"
version = "0.1.0"
description = "Simple math functions: add, multiply"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Maria Ogorodnikova", email = "ogorodnikovamaria07@gmail.com"}
]
requires-python = ">=3.9"
dependencies = []

[project.urls]
Homepage = "https://github.com/omaria123/test-git-fossdev/tree/feature/simplemath-library"
Repository = "https://github.com/omaria123/test-git-fossdev"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["simplemath"]