[tool.poetry]
name = "order-service"
version = "0.0.1"
description = "Application for serving users orders"
authors = ["metsha <ogorodnikovamaria07@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.136.1"
uvicorn = { extras = ["standard"], version = "^0.46.0" }  # ← исправлено "standart"
httpx = "^0.28.1"
psycopg = {extras = ["binary"], version = "^3.3.4"}
psycopg2-binary = "^2.9.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"